# Automatically generated massive validation regression suite.
# Contains 1012 diverse hotel aspect/department/sentiment scenarios.

import pytest
from app.services.ontology_service import OntologyService

TEST_CASES = [
    ('oda tertemizdi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda temizligi piril pirildi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('odanin temizligi kusursuzdu', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('banyo temizligi harikaydi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('yerlerin hijyeni cok temizdi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda hijyeni memnun kaldik', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda tertemizdi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda temizligi piril pirildi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('odanin temizligi kusursuzdu', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('banyo temizligi harikaydi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('yerlerin hijyeni cok temizdi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda cok pisti', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda temizligi toz icindeydi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('odanin temizligi hijyenik degildi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('banyo temizligi rezaletti', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('yerlerin hijyeni berbatti', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda hijyeni temizlenmemisti', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda cok pisti', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('oda temizligi toz icindeydi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('odanin temizligi hijyenik degildi', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('banyo temizligi rezaletti', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('yerlerin hijyeni berbatti', 'Oda Hizmetleri & Housekeeping', 'room_cleanliness'),
    ('yatak cok rahatti', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yatak konforu cok konforluydu', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yataklar mukemmeldi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yastiklar harikaydi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yastik rahatligi cok guzeldi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('dosekler deliksiz uyuttu', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yatak cok rahatti', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yatak konforu cok konforluydu', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yataklar mukemmeldi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yastiklar harikaydi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yastik rahatligi cok guzeldi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yatak cok sertti', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yatak konforu cok rahatsizdi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yataklar belimizi agritdi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yastiklar eskimisti', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yastik rahatligi yaylari bozuktu', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('dosekler hic rahat degildi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yatak cok sertti', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yatak konforu cok rahatsizdi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yataklar belimizi agritdi', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yastiklar eskimisti', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('yastik rahatligi yaylari bozuktu', 'Oda Hizmetleri & Housekeeping', 'bed_comfort'),
    ('banyo tertemizdi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('tuvalet piril pirildi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('klozet cok kullanislidir', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('dusakabin cok temizdi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('banyo lavabosu duzenliydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('dus alani iyi durumdaydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('banyo tertemizdi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('tuvalet piril pirildi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('klozet cok kullanislidir', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('dusakabin cok temizdi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('banyo lavabosu duzenliydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('banyo lekeliydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('tuvalet kirecliydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('klozet kokuyordu', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('dusakabin pislik icindeydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('banyo lavabosu cok pisti', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('dus alani temizlenmemisti', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('banyo lekeliydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('tuvalet kirecliydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('klozet kokuyordu', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('dusakabin pislik icindeydi', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('banyo lavabosu cok pisti', 'Oda Hizmetleri & Housekeeping', 'bathroom'),
    ('carsaf mis gibi kokuyordu', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('çarşaf tertemizdi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('havlu yumusacikti', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('havlular yepyeniydi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('pike piril pirildi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('nevresim cok temizdi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('yastik kilifi mis gibi kokuyordu', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('carsaf tertemizdi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('çarşaf yumusacikti', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('havlu yepyeniydi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('havlular piril pirildi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('carsaf lekeliydi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('çarşaf kirliydi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('havlu yırtıktı', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('havlular degistirilmemisti', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('pike kokuyordu', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('nevresim nemliydi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('yastik kilifi lekeliydi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('carsaf kirliydi', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('çarşaf yırtıktı', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('havlu degistirilmemisti', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('havlular kokuyordu', 'Oda Hizmetleri & Housekeeping', 'linen_towel'),
    ('oda cok genisti', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('odalar ferah ve buyuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('odamiz kocaman bir odaydi', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda boyutu cok kullanisli ve buyuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda genisligi yeterince buyuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda alani genisti', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda cok genisti', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('odalar ferah ve buyuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('odamiz kocaman bir odaydi', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda boyutu cok kullanisli ve buyuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda genisligi yeterince buyuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda cok kucuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('odalar daracikti', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('odamiz hic genis degildi', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda boyutu basikti', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda genisligi kucucuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda alani kut kutu gibiydi', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda cok kucuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('odalar daracikti', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('odamiz hic genis degildi', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda boyutu basikti', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('oda genisligi kucucuktu', 'Oda Hizmetleri & Housekeeping', 'room_size'),
    ('ses yalitimi cok basariliydi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses yalıtımı mukemmeldi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('yalitim yan odadan hic ses gelmiyordu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('duvarlar huzurluydu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses gecirmezlik sessizdi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses izolasyonu cok iyi yalitilmisti', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses yalitimi cok basariliydi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses yalıtımı mukemmeldi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('yalitim yan odadan hic ses gelmiyordu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('duvarlar huzurluydu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses gecirmezlik sessizdi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses yalitimi yetersizdi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses yalıtımı hic yoktu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('yalitim yan odadaki gurultu icerideydi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('duvarlar ses geciriyordu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses gecirmezlik berbatti', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses izolasyonu gurultu geliyordu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses yalitimi yetersizdi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses yalıtımı hic yoktu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('yalitim yan odadaki gurultu icerideydi', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('duvarlar ses geciriyordu', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('ses gecirmezlik berbatti', 'Oda Hizmetleri & Housekeeping', 'soundproofing'),
    ('sampuan kaliteliydi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('sabun bolca konulmustu', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('bornoz yeterliydi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('terlik guzel kokuyordu', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('buklet malzemesi eksiksizdi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('dus jeli tamamlanmisti', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('sampuan kaliteliydi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('sabun bolca konulmustu', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('bornoz yeterliydi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('terlik guzel kokuyordu', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('buklet malzemesi eksiksizdi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('sampuan yoktu', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('sabun eksikti', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('bornoz kalitesizdi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('terlik konulmamisti', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('buklet malzemesi bitmisti', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('dus jeli getirilmedi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('sampuan yoktu', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('sabun eksikti', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('bornoz kalitesizdi', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('terlik konulmamisti', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('buklet malzemesi bitmisti', 'Oda Hizmetleri & Housekeeping', 'amenities'),
    ('yemek cok lezzetliydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemekler sicacikti', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('aksam yemegi enfesti', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('oglen yemegi harikaydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemek kalitesi tazeydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemeklerin lezzeti cok basariliydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemek cok lezzetliydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemekler sicacikti', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('aksam yemegi enfesti', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('oglen yemegi harikaydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemek kalitesi tazeydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemek soguktu', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemekler lezzetsizdi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('aksam yemegi bayatti', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('oglen yemegi berbatti', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemek kalitesi yagliydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemeklerin lezzeti hic guzel degildi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemek soguktu', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemekler lezzetsizdi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('aksam yemegi bayatti', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('oglen yemegi berbatti', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('yemek kalitesi yagliydi', 'Yiyecek & İçecek (F&B)', 'food_quality'),
    ('kahvalti cok zengindi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvaltı cok lezzetliydi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('sabah kahvaltisi harikaydi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti cesitleri enfesti', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti sunumu kusursuzdu', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('omletler cok guzeldi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti cok zengindi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvaltı cok lezzetliydi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('sabah kahvaltisi harikaydi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti cesitleri enfesti', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti sunumu kusursuzdu', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti yetersizdi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvaltı lezzetsizdi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('sabah kahvaltisi bayatti', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti cesitleri berbatti', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti sunumu cok zayifti', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('omletler hic hosumuza gitmedi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti yetersizdi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvaltı lezzetsizdi', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('sabah kahvaltisi bayatti', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti cesitleri berbatti', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('kahvalti sunumu cok zayifti', 'Yiyecek & İçecek (F&B)', 'breakfast'),
    ('restaurant servisi cok hizliydi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restoran servisi profesyonelceydi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('masa servisi aksamadan yapildi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('tabak temizligi mukemmeldi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('garson hizi cok duzenliydi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restorandaki hiz hizli ve temizdi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restaurant servisi cok hizliydi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restoran servisi profesyonelceydi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('masa servisi aksamadan yapildi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('tabak temizligi mukemmeldi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('garson hizi cok duzenliydi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restaurant servisi cok yavasti', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restoran servisi aksiyordu', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('masa servisi masalarda catal bicak yoktu', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('tabak temizligi tabaklar kirliydi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('garson hizi berbatti', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restorandaki hiz duzensizdi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restaurant servisi cok yavasti', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('restoran servisi aksiyordu', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('masa servisi masalarda catal bicak yoktu', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('tabak temizligi tabaklar kirliydi', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('garson hizi berbatti', 'Yiyecek & İçecek (F&B)', 'restaurant_service'),
    ('menu cok zengindi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('menü bol cesitliydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('yemek cesitliligi her damak tadina uygundu', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('yemek secenekleri her gun degisiyordu', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('bufe cesidi yeterliydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('acik bufe cesitliligi tatmin ediciydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('menu cok zengindi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('menü bol cesitliydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('yemek cesitliligi her damak tadina uygundu', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('yemek secenekleri her gun degisiyordu', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('bufe cesidi yeterliydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('menu cok kisitliydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('menü her gun ayniydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('yemek cesitliligi hic cesit yoktu', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('yemek secenekleri yetersizdi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('bufe cesidi zayifti', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('acik bufe cesitliligi tekrar ediyordu', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('menu cok kisitliydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('menü her gun ayniydi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('yemek cesitliligi hic cesit yoktu', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('yemek secenekleri yetersizdi', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('bufe cesidi zayifti', 'Yiyecek & İçecek (F&B)', 'menu_variety'),
    ('icecek kaliteliydi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('içecekler orijinal markalardi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('kokteyller guzel hazirlanmisti', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('sarap enfesti', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('raki kaliteli alkol kullanilmis', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('bira cok iyiydi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('icecek kaliteliydi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('içecekler orijinal markalardi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('kokteyller guzel hazirlanmisti', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('sarap enfesti', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('raki kaliteli alkol kullanilmis', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('icecek kalitesizdi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('içecekler sulandirilmisti', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('kokteyller asitsizdi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('sarap ucuz markalardi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('raki berbatti', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('bira hic begenmedik', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('icecek kalitesizdi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('içecekler sulandirilmisti', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('kokteyller asitsizdi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('sarap ucuz markalardi', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('raki berbatti', 'Yiyecek & İçecek (F&B)', 'drink_quality'),
    ('minibar her gun dolduruluyordu', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('mini bar zengindi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('odadaki buzdolabi sogutuyordu', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar cesitliligi eksiksizdi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar icecekleri cok yeterliydi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar duzenli takip ediliyordu', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('mini bar her gun dolduruluyordu', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('odadaki buzdolabi zengindi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar cesitliligi sogutuyordu', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar icecekleri eksiksizdi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar cok yeterliydi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar bos birakilmisti', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('mini bar sogutmuyordu', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('odadaki buzdolabi eksikti', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar cesitliligi doldurulmadi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar icecekleri yetersizdi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar hic yoktu', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('mini bar bos birakilmisti', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('odadaki buzdolabi sogutmuyordu', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar cesitliligi eksikti', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar icecekleri doldurulmadi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('minibar yetersizdi', 'Yiyecek & İçecek (F&B)', 'minibar'),
    ('yemek sirasi hic yoktu', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bar kuyrugu sira beklemiyorduk', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('restorandaki sira cok hizli ilerliyordu', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bekleme suresi sorunsuzdu', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bufedeki kuyruklar rahatti', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('sira bekleme akiciydi', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('yemek sirasi hic yoktu', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bar kuyrugu sira beklemiyorduk', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('restorandaki sira cok hizli ilerliyordu', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bekleme suresi sorunsuzdu', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bufedeki kuyruklar rahatti', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('yemek sirasi dakikalarca suruyordu', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bar kuyrugu asiri kalabalikti', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('restorandaki sira kuyruklar bezdirdi', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bekleme suresi cekilmezdi', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bufedeki kuyruklar rezaletti', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('sira bekleme cok bekledik', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('yemek sirasi dakikalarca suruyordu', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bar kuyrugu asiri kalabalikti', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('restorandaki sira kuyruklar bezdirdi', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bekleme suresi cekilmezdi', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('bufedeki kuyruklar rezaletti', 'Yiyecek & İçecek (F&B)', 'queue_waiting'),
    ('check-in cok hizliydi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('check-out sorunsuz gerceklesti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('giris islemi hizlica halledildi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('cikis islemi pratikti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('oda teslimi kolaydi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('giris ve cikislar saniyeler surdu', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('check-in cok hizliydi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('check-out sorunsuz gerceklesti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('giris islemi hizlica halledildi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('cikis islemi pratikti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('oda teslimi kolaydi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('check-in cok yavasti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('check-out saatlerce bekledik', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('giris islemi iskence gibiydi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('cikis islemi karmasikti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('oda teslimi geciktirildi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('giris ve cikislar rezaletti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('check-in cok yavasti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('check-out saatlerce bekledik', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('giris islemi iskence gibiydi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('cikis islemi karmasikti', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('oda teslimi geciktirildi', 'Ön Büro & Misafir İlişkileri', 'check_in_out'),
    ('resepsiyon cok yardimseverdi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon hizmeti profesyoneldi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('misafir iliskileri ilgililerdi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('guest relations guler yuzlu karsiladi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('lobi hizmeti cok kibardi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon cozum odakliydi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon hizmeti cok yardimseverdi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('misafir iliskileri profesyoneldi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('guest relations ilgililerdi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('lobi hizmeti guler yuzlu karsiladi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon cok kibardi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon kaba davrandi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon hizmeti ilgisizdi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('misafir iliskileri cevap vermedi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('guest relations yavasti', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('lobi hizmeti kustahcaydi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon suratsizdi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon hizmeti kaba davrandi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('misafir iliskileri ilgisizdi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('guest relations cevap vermedi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('lobi hizmeti yavasti', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('resepsiyon kustahcaydi', 'Ön Büro & Misafir İlişkileri', 'reception_service'),
    ('rezervasyon sorunsuz gorunuyordu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('booking aninda bulundu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('overbooking eksiksiz girilmisti', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('oda kaydi hizlica onaylandi', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon islemi duzenliydi', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon dogruydu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('booking sorunsuz gorunuyordu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('overbooking aninda bulundu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('oda kaydi eksiksiz girilmisti', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon islemi hizlica onaylandi', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon duzenliydi', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon gorunmuyordu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('booking yanlis yapilmisti', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('overbooking overbooking olmustuk', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('oda kaydi iptal edilmisti', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon islemi kaybolmustu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon karismisti', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('booking gorunmuyordu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('overbooking yanlis yapilmisti', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('oda kaydi overbooking olmustuk', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon islemi iptal edilmisti', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('rezervasyon kaybolmustu', 'Ön Büro & Misafir İlişkileri', 'booking'),
    ('fiyat performans cok iyiydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('paranin karsiligi hak ediyordu', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('ucret dengesi uygundu', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('odenen miktar kesinlikle degerdi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performansi fiyatina gore harikaydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performans yerindeydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('paranin karsiligi cok iyiydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('ucret dengesi hak ediyordu', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('odenen miktar uygundu', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performansi kesinlikle degerdi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performans fiyatina gore harikaydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performans degmezdi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('paranin karsiligi paramiz cop oldu', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('ucret dengesi cok pahaliydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('odenen miktar fahisti', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performansi para tuzagiydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performans israfti', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('paranin karsiligi degmezdi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('ucret dengesi paramiz cop oldu', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('odenen miktar cok pahaliydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performansi fahisti', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fiyat performans para tuzagiydi', 'Ön Büro & Misafir İlişkileri', 'price_value'),
    ('fatura dogru cikti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('odeme aninda iade edildi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('ödeme sorunsuz halledildi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('depozito iadesi nettir', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('ekstra ucretler dogru hesaplanmisti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('hesap detayi duzenliydi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('fatura dogru cikti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('odeme aninda iade edildi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('ödeme sorunsuz halledildi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('depozito iadesi nettir', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('ekstra ucretler dogru hesaplanmisti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('fatura hataliydi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('odeme iade edilmedi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('ödeme yanlis hesaplanmisti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('depozito iadesi fazla cekilmisti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('ekstra ucretler karmasikti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('hesap detayi eksikti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('fatura hataliydi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('odeme iade edilmedi', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('ödeme yanlis hesaplanmisti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('depozito iadesi fazla cekilmisti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('ekstra ucretler karmasikti', 'Ön Büro & Misafir İlişkileri', 'billing'),
    ('sikayet cozumu cok basariliydi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sorunlarin cozumu aninda cozuldu', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('misafir iliskileri ilgisi telafi edildi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayetlerin dikkate alinmasi yardimci oldular', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('cozum hizi harikaydi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayet cozumu cozum odakliydi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sorunlarin cozumu cok basariliydi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('misafir iliskileri ilgisi aninda cozuldu', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayetlerin dikkate alinmasi telafi edildi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('cozum hizi yardimci oldular', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayet cozumu harikaydi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayet cozumu hic yoktu', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sorunlarin cozumu dikkate alinmadi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('misafir iliskileri ilgisi cozulmedi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayetlerin dikkate alinmasi baslarindan savdilar', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('cozum hizi ilgisizlerdi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayet cozumu cozum uretilmedi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sorunlarin cozumu hic yoktu', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('misafir iliskileri ilgisi dikkate alinmadi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayetlerin dikkate alinmasi cozulmedi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('cozum hizi baslarindan savdilar', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('sikayet cozumu ilgisizlerdi', 'Ön Büro & Misafir İlişkileri', 'complaint_resolution'),
    ('klima harika sogutuyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima sistemi sessiz ve guzel calisiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('iklimlendirme cok iyiydi', 'Teknik Servis & IT', 'air_conditioning'),
    ('klimanin sogutmasi sorunsuz calisiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima motoru buzz gibi yapiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima mukemmeldi', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima sistemi harika sogutuyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('iklimlendirme sessiz ve guzel calisiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klimanin sogutmasi cok iyiydi', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima motoru sorunsuz calisiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima buzz gibi yapiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima sogutmuyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima sistemi bozuktu', 'Teknik Servis & IT', 'air_conditioning'),
    ('iklimlendirme arizaliydi', 'Teknik Servis & IT', 'air_conditioning'),
    ('klimanin sogutmasi gurultulu calisiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima motoru su damlatiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima hic calismiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima sistemi sogutmuyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('iklimlendirme bozuktu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klimanin sogutmasi arizaliydi', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima motoru gurultulu calisiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('klima su damlatiyordu', 'Teknik Servis & IT', 'air_conditioning'),
    ('wifi cok hizliydi', 'Teknik Servis & IT', 'wifi_internet'),
    ('wi-fi hic kopmuyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('internet kesintisizdi', 'Teknik Servis & IT', 'wifi_internet'),
    ('internet baglantisi her yerde cekiyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('odadaki internet cok basariliydi', 'Teknik Servis & IT', 'wifi_internet'),
    ('wifi gayet akiciydi', 'Teknik Servis & IT', 'wifi_internet'),
    ('wi-fi cok hizliydi', 'Teknik Servis & IT', 'wifi_internet'),
    ('internet hic kopmuyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('internet baglantisi kesintisizdi', 'Teknik Servis & IT', 'wifi_internet'),
    ('odadaki internet her yerde cekiyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('wifi cok basariliydi', 'Teknik Servis & IT', 'wifi_internet'),
    ('wifi surekli kopuyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('wi-fi cok yavasti', 'Teknik Servis & IT', 'wifi_internet'),
    ('internet baglanilmiyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('internet baglantisi hic cekmiyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('odadaki internet berbatti', 'Teknik Servis & IT', 'wifi_internet'),
    ('wifi yetersizdi', 'Teknik Servis & IT', 'wifi_internet'),
    ('wi-fi surekli kopuyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('internet cok yavasti', 'Teknik Servis & IT', 'wifi_internet'),
    ('internet baglantisi baglanilmiyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('odadaki internet hic cekmiyordu', 'Teknik Servis & IT', 'wifi_internet'),
    ('wifi berbatti', 'Teknik Servis & IT', 'wifi_internet'),
    ('televizyon sorunsuz calisiyordu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv guzel yayin vardi', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv kumandasi kumanda saglamdi', 'Teknik Servis & IT', 'tv_entertainment'),
    ('kanal yayinlari guzeldi', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv ekranı kesintisizdi', 'Teknik Servis & IT', 'tv_entertainment'),
    ('televizyon netti', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv sorunsuz calisiyordu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv kumandasi guzel yayin vardi', 'Teknik Servis & IT', 'tv_entertainment'),
    ('kanal yayinlari kumanda saglamdi', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv ekranı guzeldi', 'Teknik Servis & IT', 'tv_entertainment'),
    ('televizyon kesintisizdi', 'Teknik Servis & IT', 'tv_entertainment'),
    ('televizyon bozuktu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv calismiyordu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv kumandasi kumanda kirikti', 'Teknik Servis & IT', 'tv_entertainment'),
    ('kanal yayinlari kanallar cekmiyordu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv ekranı sinyal yoktu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('televizyon yoktu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv bozuktu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv kumandasi calismiyordu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('kanal yayinlari kumanda kirikti', 'Teknik Servis & IT', 'tv_entertainment'),
    ('tv ekranı kanallar cekmiyordu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('televizyon sinyal yoktu', 'Teknik Servis & IT', 'tv_entertainment'),
    ('asansor cok hizliydi', 'Teknik Servis & IT', 'elevator'),
    ('asansörler sorunsuz calisiyordu', 'Teknik Servis & IT', 'elevator'),
    ('lift genis ve temizdi', 'Teknik Servis & IT', 'elevator'),
    ('asansor sistemi guzel calisiyordu', 'Teknik Servis & IT', 'elevator'),
    ('asansor hizi güvenliydi', 'Teknik Servis & IT', 'elevator'),
    ('asansor akiciydi', 'Teknik Servis & IT', 'elevator'),
    ('asansörler cok hizliydi', 'Teknik Servis & IT', 'elevator'),
    ('lift sorunsuz calisiyordu', 'Teknik Servis & IT', 'elevator'),
    ('asansor sistemi genis ve temizdi', 'Teknik Servis & IT', 'elevator'),
    ('asansor hizi guzel calisiyordu', 'Teknik Servis & IT', 'elevator'),
    ('asansor güvenliydi', 'Teknik Servis & IT', 'elevator'),
    ('asansor surekli arizalaniyordu', 'Teknik Servis & IT', 'elevator'),
    ('asansörler bozuktu', 'Teknik Servis & IT', 'elevator'),
    ('lift cok yavasti', 'Teknik Servis & IT', 'elevator'),
    ('asansor sistemi hic calismiyordu', 'Teknik Servis & IT', 'elevator'),
    ('asansor hizi tehlikeliydi', 'Teknik Servis & IT', 'elevator'),
    ('asansor yetersizdi', 'Teknik Servis & IT', 'elevator'),
    ('asansörler surekli arizalaniyordu', 'Teknik Servis & IT', 'elevator'),
    ('lift bozuktu', 'Teknik Servis & IT', 'elevator'),
    ('asansor sistemi cok yavasti', 'Teknik Servis & IT', 'elevator'),
    ('asansor hizi hic calismiyordu', 'Teknik Servis & IT', 'elevator'),
    ('asansor tehlikeliydi', 'Teknik Servis & IT', 'elevator'),
    ('sicak su sorunsuz calisiyordu', 'Teknik Servis & IT', 'maintenance'),
    ('musluklar yeni gibiydi', 'Teknik Servis & IT', 'maintenance'),
    ('dus basligi bakimliydi', 'Teknik Servis & IT', 'maintenance'),
    ('prizler sorun cikarmadi', 'Teknik Servis & IT', 'maintenance'),
    ('elektrik tesisati duzenli bakilmisti', 'Teknik Servis & IT', 'maintenance'),
    ('oda bakimi saglamdi', 'Teknik Servis & IT', 'maintenance'),
    ('sicak su sorunsuz calisiyordu', 'Teknik Servis & IT', 'maintenance'),
    ('musluklar yeni gibiydi', 'Teknik Servis & IT', 'maintenance'),
    ('dus basligi bakimliydi', 'Teknik Servis & IT', 'maintenance'),
    ('prizler sorun cikarmadi', 'Teknik Servis & IT', 'maintenance'),
    ('elektrik tesisati duzenli bakilmisti', 'Teknik Servis & IT', 'maintenance'),
    ('sicak su akmiyordu', 'Teknik Servis & IT', 'maintenance'),
    ('musluklar bozuktu', 'Teknik Servis & IT', 'maintenance'),
    ('dus basligi arizaliydi', 'Teknik Servis & IT', 'maintenance'),
    ('prizler tamir edilmeli', 'Teknik Servis & IT', 'maintenance'),
    ('elektrik tesisati calismiyordu', 'Teknik Servis & IT', 'maintenance'),
    ('oda bakimi eskimisti ve calismiyordu', 'Teknik Servis & IT', 'maintenance'),
    ('sicak su akmiyordu', 'Teknik Servis & IT', 'maintenance'),
    ('musluklar bozuktu', 'Teknik Servis & IT', 'maintenance'),
    ('dus basligi arizaliydi', 'Teknik Servis & IT', 'maintenance'),
    ('prizler tamir edilmeli', 'Teknik Servis & IT', 'maintenance'),
    ('elektrik tesisati calismiyordu', 'Teknik Servis & IT', 'maintenance'),
    ('havuz tertemizdi', 'Rekreasyon & Eğlence', 'pool'),
    ('yuzme havuzu cok eglenceliydi', 'Rekreasyon & Eğlence', 'pool'),
    ('aquapark piril pirildi', 'Rekreasyon & Eğlence', 'pool'),
    ('aquaprk bakimliydi', 'Rekreasyon & Eğlence', 'pool'),
    ('su kaydiraklari buyuk ve guzeldi', 'Rekreasyon & Eğlence', 'pool'),
    ('havuz alani guzel temizleniyordu', 'Rekreasyon & Eğlence', 'pool'),
    ('havuz tertemizdi', 'Rekreasyon & Eğlence', 'pool'),
    ('yuzme havuzu cok eglenceliydi', 'Rekreasyon & Eğlence', 'pool'),
    ('aquapark piril pirildi', 'Rekreasyon & Eğlence', 'pool'),
    ('aquaprk bakimliydi', 'Rekreasyon & Eğlence', 'pool'),
    ('su kaydiraklari buyuk ve guzeldi', 'Rekreasyon & Eğlence', 'pool'),
    ('havuz kirliydi', 'Rekreasyon & Eğlence', 'pool'),
    ('yuzme havuzu klor kokuyordu', 'Rekreasyon & Eğlence', 'pool'),
    ('aquapark bakimsizdi', 'Rekreasyon & Eğlence', 'pool'),
    ('aquaprk cok kucuktu', 'Rekreasyon & Eğlence', 'pool'),
    ('su kaydiraklari pislik icindeydi', 'Rekreasyon & Eğlence', 'pool'),
    ('havuz alani hic hijyenik degildi', 'Rekreasyon & Eğlence', 'pool'),
    ('havuz kirliydi', 'Rekreasyon & Eğlence', 'pool'),
    ('yuzme havuzu klor kokuyordu', 'Rekreasyon & Eğlence', 'pool'),
    ('aquapark bakimsizdi', 'Rekreasyon & Eğlence', 'pool'),
    ('aquaprk cok kucuktu', 'Rekreasyon & Eğlence', 'pool'),
    ('su kaydiraklari pislik icindeydi', 'Rekreasyon & Eğlence', 'pool'),
    ('spa harikaydi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('masaj cok rahatlaticiydi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('sauna profesyonelce yapildi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('hamam mukemmeldi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('jakuzi temiz ve huzurluydu', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('masaj salonu cok basariliydi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('spa harikaydi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('masaj cok rahatlaticiydi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('sauna profesyonelce yapildi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('hamam mukemmeldi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('jakuzi temiz ve huzurluydu', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('spa berbatti', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('masaj pislik icindeydi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('sauna terapistler kaba davrandi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('hamam soguktu', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('jakuzi yetersizdi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('masaj salonu hic profesyonel degildi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('spa berbatti', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('masaj pislik icindeydi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('sauna terapistler kaba davrandi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('hamam soguktu', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('jakuzi yetersizdi', 'Rekreasyon & Eğlence', 'spa_massage'),
    ('animasyon ekibi cok eglenceliydi', 'Rekreasyon & Eğlence', 'animation'),
    ('aksam sovlar cok dinamikti', 'Rekreasyon & Eğlence', 'animation'),
    ('canli muzik harikaydi', 'Rekreasyon & Eğlence', 'animation'),
    ('konserler keyifliydi', 'Rekreasyon & Eğlence', 'animation'),
    ('gun boyu aktiviteler cok basariliydi', 'Rekreasyon & Eğlence', 'animation'),
    ('gosteriler mukemmeldi', 'Rekreasyon & Eğlence', 'animation'),
    ('animasyon ekibi cok eglenceliydi', 'Rekreasyon & Eğlence', 'animation'),
    ('aksam sovlar cok dinamikti', 'Rekreasyon & Eğlence', 'animation'),
    ('canli muzik harikaydi', 'Rekreasyon & Eğlence', 'animation'),
    ('konserler keyifliydi', 'Rekreasyon & Eğlence', 'animation'),
    ('gun boyu aktiviteler cok basariliydi', 'Rekreasyon & Eğlence', 'animation'),
    ('animasyon ekibi cok sönüktü', 'Rekreasyon & Eğlence', 'animation'),
    ('aksam sovlar sıkıcıydı', 'Rekreasyon & Eğlence', 'animation'),
    ('canli muzik berbatti', 'Rekreasyon & Eğlence', 'animation'),
    ('konserler yetersizdi', 'Rekreasyon & Eğlence', 'animation'),
    ('gun boyu aktiviteler gurultuluydu', 'Rekreasyon & Eğlence', 'animation'),
    ('gosteriler hic yok gibiydi', 'Rekreasyon & Eğlence', 'animation'),
    ('animasyon ekibi cok sönüktü', 'Rekreasyon & Eğlence', 'animation'),
    ('aksam sovlar sıkıcıydı', 'Rekreasyon & Eğlence', 'animation'),
    ('canli muzik berbatti', 'Rekreasyon & Eğlence', 'animation'),
    ('konserler yetersizdi', 'Rekreasyon & Eğlence', 'animation'),
    ('gun boyu aktiviteler gurultuluydu', 'Rekreasyon & Eğlence', 'animation'),
    ('plaj muhtesemdi', 'Rekreasyon & Eğlence', 'beach'),
    ('deniz piril pirildi', 'Rekreasyon & Eğlence', 'beach'),
    ('kumsal kum plaj cok guzeldi', 'Rekreasyon & Eğlence', 'beach'),
    ('sahil temiz ve berrakti', 'Rekreasyon & Eğlence', 'beach'),
    ('deniz temizligi cok guzeldi', 'Rekreasyon & Eğlence', 'beach'),
    ('iskele harikaydi', 'Rekreasyon & Eğlence', 'beach'),
    ('plaj muhtesemdi', 'Rekreasyon & Eğlence', 'beach'),
    ('deniz piril pirildi', 'Rekreasyon & Eğlence', 'beach'),
    ('kumsal kum plaj cok guzeldi', 'Rekreasyon & Eğlence', 'beach'),
    ('sahil temiz ve berrakti', 'Rekreasyon & Eğlence', 'beach'),
    ('deniz temizligi cok guzeldi', 'Rekreasyon & Eğlence', 'beach'),
    ('plaj taslikti', 'Rekreasyon & Eğlence', 'beach'),
    ('deniz yosunluydu', 'Rekreasyon & Eğlence', 'beach'),
    ('kumsal kirliydi', 'Rekreasyon & Eğlence', 'beach'),
    ('sahil dalgalı ve pisti', 'Rekreasyon & Eğlence', 'beach'),
    ('deniz temizligi uzakti', 'Rekreasyon & Eğlence', 'beach'),
    ('iskele bakimsizdi', 'Rekreasyon & Eğlence', 'beach'),
    ('plaj taslikti', 'Rekreasyon & Eğlence', 'beach'),
    ('deniz yosunluydu', 'Rekreasyon & Eğlence', 'beach'),
    ('kumsal kirliydi', 'Rekreasyon & Eğlence', 'beach'),
    ('sahil dalgalı ve pisti', 'Rekreasyon & Eğlence', 'beach'),
    ('deniz temizligi uzakti', 'Rekreasyon & Eğlence', 'beach'),
    ('cocuk kulubu cok eglenceliydi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('mini club cocuklar cok sevdi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('miniclub aktiviteler zengindi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk oyun alani guvenliydi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('kids club harikaydi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk kulubu eglenceli gecti', 'Rekreasyon & Eğlence', 'kids_club'),
    ('mini club cok eglenceliydi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('miniclub cocuklar cok sevdi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk oyun alani aktiviteler zengindi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('kids club guvenliydi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk kulubu harikaydi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk kulubu kapaliydi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('mini club yetersizdi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('miniclub ilgilenen kimse yoktu', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk oyun alani bakimsizdi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('kids club cok kucuktu', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk kulubu hic guvenli degildi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('mini club kapaliydi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('miniclub yetersizdi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk oyun alani ilgilenen kimse yoktu', 'Rekreasyon & Eğlence', 'kids_club'),
    ('kids club bakimsizdi', 'Rekreasyon & Eğlence', 'kids_club'),
    ('cocuk kulubu cok kucuktu', 'Rekreasyon & Eğlence', 'kids_club'),
    ('fitness salonu modern ve temizdi', 'Rekreasyon & Eğlence', 'fitness'),
    ('gym yeterliydi', 'Rekreasyon & Eğlence', 'fitness'),
    ('spor salonu aletler yeniydi', 'Rekreasyon & Eğlence', 'fitness'),
    ('tenis kortu cok guzeldi', 'Rekreasyon & Eğlence', 'fitness'),
    ('spor aletleri kullanisliydi', 'Rekreasyon & Eğlence', 'fitness'),
    ('fitness salonu bakimliydi', 'Rekreasyon & Eğlence', 'fitness'),
    ('gym modern ve temizdi', 'Rekreasyon & Eğlence', 'fitness'),
    ('spor salonu yeterliydi', 'Rekreasyon & Eğlence', 'fitness'),
    ('tenis kortu aletler yeniydi', 'Rekreasyon & Eğlence', 'fitness'),
    ('spor aletleri cok guzeldi', 'Rekreasyon & Eğlence', 'fitness'),
    ('fitness salonu kullanisliydi', 'Rekreasyon & Eğlence', 'fitness'),
    ('fitness salonu aletler bozuktu', 'Rekreasyon & Eğlence', 'fitness'),
    ('gym cok kucuktu', 'Rekreasyon & Eğlence', 'fitness'),
    ('spor salonu yetersizdi', 'Rekreasyon & Eğlence', 'fitness'),
    ('tenis kortu bakimsizdi', 'Rekreasyon & Eğlence', 'fitness'),
    ('spor aletleri sicakti', 'Rekreasyon & Eğlence', 'fitness'),
    ('fitness salonu eskimisti', 'Rekreasyon & Eğlence', 'fitness'),
    ('gym aletler bozuktu', 'Rekreasyon & Eğlence', 'fitness'),
    ('spor salonu cok kucuktu', 'Rekreasyon & Eğlence', 'fitness'),
    ('tenis kortu yetersizdi', 'Rekreasyon & Eğlence', 'fitness'),
    ('spor aletleri bakimsizdi', 'Rekreasyon & Eğlence', 'fitness'),
    ('fitness salonu sicakti', 'Rekreasyon & Eğlence', 'fitness'),
    ('bahce cok guzeldi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('bahçe bakimli ve temizdi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('peyzaj huzur vericiydi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('yesil alanlar yeşillikler icindeydi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('otel mimarisi harikaydi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('mimari tasarim duzenliydi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('bahce cok guzeldi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('bahçe bakimli ve temizdi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('peyzaj huzur vericiydi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('yesil alanlar yeşillikler icindeydi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('otel mimarisi harikaydi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('bahce bakimsizdi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('bahçe kurumustu', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('peyzaj cop doluydu', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('yesil alanlar karmasikti', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('otel mimarisi duzensizdi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('mimari tasarim hic hos degildi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('bahce bakimsizdi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('bahçe kurumustu', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('peyzaj cop doluydu', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('yesil alanlar karmasikti', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('otel mimarisi duzensizdi', 'Çevre, Güvenlik & Ulaşım', 'environment'),
    ('otopark genis ve yeterliydi', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('park yeri cok hizli yardimci oldu', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('vale hizmeti sorunsuzdu', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('valet guvenliydi', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('araba park alani ucretsiz ve genisti', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('otopark rahatti', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('park yeri genis ve yeterliydi', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('vale hizmeti cok hizli yardimci oldu', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('valet sorunsuzdu', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('araba park alani guvenliydi', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('otopark ucretsiz ve genisti', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('otopark yetersizdi', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('park yeri yer bulamadik', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('vale hizmeti vale cok bekletti', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('valet sorunluydu', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('araba park alani cok kucuktu', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('otopark guvensizdi', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('park yeri yetersizdi', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('vale hizmeti yer bulamadik', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('valet vale cok bekletti', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('araba park alani sorunluydu', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('otopark cok kucuktu', 'Çevre, Güvenlik & Ulaşım', 'parking'),
    ('güvenlik cok sıkıydı', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('kamera sistemi güven vericiydi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('bekci her yerde kamera vardi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('otel guvenligi profesyoneldi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('kilit sistemi kusursuzdu', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('güvenlik iyi durumdaydi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('kamera sistemi cok sıkıydı', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('bekci güven vericiydi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('otel guvenligi her yerde kamera vardi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('kilit sistemi profesyoneldi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('güvenlik kusursuzdu', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('güvenlik yetersizdi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('kamera sistemi hic yoktu', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('bekci guvensiz hissettirdi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('otel guvenligi kameralar calismiyordu', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('kilit sistemi zayifti', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('güvenlik gevsekti', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('kamera sistemi yetersizdi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('bekci hic yoktu', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('otel guvenligi guvensiz hissettirdi', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('kilit sistemi kameralar calismiyordu', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('güvenlik zayifti', 'Çevre, Güvenlik & Ulaşım', 'security'),
    ('transfer hizmeti cok dakikti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('shuttle servisi konforluydu', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('ulasim imkanlari hizli ve rahatti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('havalimani transferi sorunsuz gerceklesti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('taksi bulma cok kolaydi', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('transfer hizmeti mukemmeldi', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('shuttle servisi cok dakikti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('ulasim imkanlari konforluydu', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('havalimani transferi hizli ve rahatti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('taksi bulma sorunsuz gerceklesti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('transfer hizmeti cok kolaydi', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('transfer hizmeti gecikti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('shuttle servisi yavasti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('ulasim imkanlari arac cok eskiydi', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('havalimani transferi iptal edildi', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('taksi bulma sorunluydu', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('transfer hizmeti pahaliydi', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('shuttle servisi gecikti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('ulasim imkanlari yavasti', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('havalimani transferi arac cok eskiydi', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('taksi bulma iptal edildi', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('transfer hizmeti sorunluydu', 'Çevre, Güvenlik & Ulaşım', 'transportation'),
    ('otel konumu harikaydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('lokasyon her yere cok yakindi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('merkeze yakinlik denize sifirdi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('konum mukemmel konumdaydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('cevre konumu cok merkeziydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('otel konumu cok iyiydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('lokasyon harikaydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('merkeze yakinlik her yere cok yakindi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('konum denize sifirdi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('cevre konumu mukemmel konumdaydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('otel konumu cok merkeziydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('otel konumu cok uzakti', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('lokasyon ulasimi zordu', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('merkeze yakinlik dagin basindaydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('konum sapa bir yerdeydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('cevre konumu merkeze cok uzakti', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('otel konumu iyi degildi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('lokasyon cok uzakti', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('merkeze yakinlik ulasimi zordu', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('konum dagin basindaydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('cevre konumu sapa bir yerdeydi', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('otel konumu merkeze cok uzakti', 'Çevre, Güvenlik & Ulaşım', 'location'),
    ('manzara muhtesemdi', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('deniz manzarasi harikaydi', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('doga manzarasi insani buyuluyordu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('oda manzarasi guzeldi', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('balkon manzarasi kesintisiz ve acikti', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('manzara mukemmeldi', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('deniz manzarasi muhtesemdi', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('doga manzarasi harikaydi', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('oda manzarasi insani buyuluyordu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('balkon manzarasi guzeldi', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('manzara kesintisiz ve acikti', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('manzara kapatilmisti', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('deniz manzarasi hic yoktu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('doga manzarasi duvara bakiyordu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('oda manzarasi cok kotuydu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('balkon manzarasi bina görüyordu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('manzara kasvetydi', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('deniz manzarasi kapatilmisti', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('doga manzarasi hic yoktu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('oda manzarasi duvara bakiyordu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('balkon manzarasi cok kotuydu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('manzara bina görüyordu', 'Çevre, Güvenlik & Ulaşım', 'view'),
    ('gurultu seviyesi cok sessizdi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('ses gurultusu huzur vericiydi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('sessizlik kafa dinlemek icin idealdi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('oda gurultusu cok sakindi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('ses yuksekligi guzel kafa dinletti', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('gurultu seviyesi sessiz ve sakindi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('ses gurultusu cok sessizdi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('sessizlik huzur vericiydi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('oda gurultusu kafa dinlemek icin idealdi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('ses yuksekligi cok sakindi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('gurultu seviyesi guzel kafa dinletti', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('gurultu seviyesi cok yuksekti', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('ses gurultusu gece uyutmiyordu', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('sessizlik gurultuluydu', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('oda gurultusu kafa agritiyordu', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('ses yuksekligi cekilmezdi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('gurultu seviyesi rahatsiz ediciydi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('ses gurultusu cok yuksekti', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('sessizlik gece uyutmiyordu', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('oda gurultusu gurultuluydu', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('ses yuksekligi kafa agritiyordu', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('gurultu seviyesi cekilmezdi', 'Otel Atmosferi & Misafir Profili', 'noise_level'),
    ('otel kalabaligi cok sakindi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('tesisin yogunlugu asiri yogun degildi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('kalabalik seviyesi rahatsiz etmiyordu', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('insan sayisi gayet iyiydi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('yogunluk duzenliydi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('otel kalabaligi kaotik degildi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('tesisin yogunlugu cok sakindi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('kalabalik seviyesi asiri yogun degildi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('insan sayisi rahatsiz etmiyordu', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('yogunluk gayet iyiydi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('otel kalabaligi duzenliydi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('otel kalabaligi asiri fazlaydi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('tesisin yogunlugu her yer ana baba gunuydu', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('kalabalik seviyesi kaos vardi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('insan sayisi bezdirdi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('yogunluk hic sakin degildi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('otel kalabaligi cekilmezdi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('tesisin yogunlugu asiri fazlaydi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('kalabalik seviyesi her yer ana baba gunuydu', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('insan sayisi kaos vardi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('yogunluk bezdirdi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('otel kalabaligi hic sakin degildi', 'Otel Atmosferi & Misafir Profili', 'crowd'),
    ('misafir profili cok kaliteliydi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('kitle kalitesi saygili insanlardi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('gelen turistler nezih bir kitleydi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('musteri portfoyu cok iyiydi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('oteldeki kitle saygiliydi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('misafir profili seckindi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('kitle kalitesi cok kaliteliydi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('gelen turistler saygili insanlardi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('musteri portfoyu nezih bir kitleydi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('oteldeki kitle cok iyiydi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('misafir profili saygiliydi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('misafir profili saygisizdi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('kitle kalitesi seviyesizdi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('gelen turistler hic nezih degildi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('musteri portfoyu kaba misafirler vardi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('oteldeki kitle kotuydu', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('misafir profili rahatsiz edici kitle vardi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('kitle kalitesi saygisizdi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('gelen turistler seviyesizdi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('musteri portfoyu hic nezih degildi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('oteldeki kitle kaba misafirler vardi', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('misafir profili kotuydu', 'Otel Atmosferi & Misafir Profili', 'guest_profile'),
    ('otel atmosferi cok huzurluydu', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('ortam dinlendiriciydi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('huzurlu ortam harikaydi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('genel hava cok sicakti', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('ambiyans cok guzeldi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('otel atmosferi buyuleyiciydi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('ortam cok huzurluydu', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('huzurlu ortam dinlendiriciydi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('genel hava harikaydi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('ambiyans cok sicakti', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('otel atmosferi cok guzeldi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('otel atmosferi kaotikti', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('ortam kasvetliydi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('huzurlu ortam huzursuzdu', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('genel hava basiti', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('ambiyans berbatti', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('otel atmosferi kasvet vericiydi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('ortam kaotikti', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('huzurlu ortam kasvetliydi', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('genel hava huzursuzdu', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('ambiyans basiti', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('otel atmosferi berbatti', 'Otel Atmosferi & Misafir Profili', 'general_atmosphere'),
    ('otel yonetimi cok profesyoneldi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('isletme kalitesi basariliydi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('organizasyon kusursuz organize edilmisti', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('yonetim sekli iyi isletiliyordu', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel isletmesi cok iyiydi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel yonetimi organizeydi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('isletme kalitesi cok profesyoneldi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('organizasyon basariliydi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('yonetim sekli kusursuz organize edilmisti', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel isletmesi iyi isletiliyordu', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel yonetimi cok iyiydi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel yonetimi cok kotuydu', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('isletme kalitesi hic organize degildi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('organizasyon yonetim zaafiyeti vardi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('yonetim sekli is bilmezlerdi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel isletmesi rezaletti', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel yonetimi berbatti', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('isletme kalitesi cok kotuydu', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('organizasyon hic organize degildi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('yonetim sekli yonetim zaafiyeti vardi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel isletmesi is bilmezlerdi', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('otel yonetimi rezaletti', 'Otel Atmosferi & Misafir Profili', 'general_management'),
    ('personel tutumu cok kibardi', 'Personel Davranışı', 'staff_attitude'),
    ('calisanlarin tavri guler yuzluydu', 'Personel Davranışı', 'staff_attitude'),
    ('personel ilgisi sicakkanliydi', 'Personel Davranışı', 'staff_attitude'),
    ('garsonlarin tavirlari saygiliydi', 'Personel Davranışı', 'staff_attitude'),
    ('resepsiyon tavri nazikti', 'Personel Davranışı', 'staff_attitude'),
    ('personel tutumu hürmetkarca karsiladi', 'Personel Davranışı', 'staff_attitude'),
    ('calisanlarin tavri cok kibardi', 'Personel Davranışı', 'staff_attitude'),
    ('personel ilgisi guler yuzluydu', 'Personel Davranışı', 'staff_attitude'),
    ('garsonlarin tavirlari sicakkanliydi', 'Personel Davranışı', 'staff_attitude'),
    ('resepsiyon tavri saygiliydi', 'Personel Davranışı', 'staff_attitude'),
    ('personel tutumu nazikti', 'Personel Davranışı', 'staff_attitude'),
    ('personel tutumu kaba davrandilar', 'Personel Davranışı', 'staff_attitude'),
    ('calisanlarin tavri lakayitti', 'Personel Davranışı', 'staff_attitude'),
    ('personel ilgisi saygisizdi', 'Personel Davranışı', 'staff_attitude'),
    ('garsonlarin tavirlari suratsizdi', 'Personel Davranışı', 'staff_attitude'),
    ('resepsiyon tavri ilgisizdi', 'Personel Davranışı', 'staff_attitude'),
    ('personel tutumu terbiyesizdi', 'Personel Davranışı', 'staff_attitude'),
    ('calisanlarin tavri kaba davrandilar', 'Personel Davranışı', 'staff_attitude'),
    ('personel ilgisi lakayitti', 'Personel Davranışı', 'staff_attitude'),
    ('garsonlarin tavirlari saygisizdi', 'Personel Davranışı', 'staff_attitude'),
    ('resepsiyon tavri suratsizdi', 'Personel Davranışı', 'staff_attitude'),
    ('personel tutumu ilgisizdi', 'Personel Davranışı', 'staff_attitude'),
    ('personel hizmeti cok hizliydi', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti mukemmeldi', 'Personel Davranışı', 'staff_service'),
    ('yardimseverlik aninda yardimci oldular', 'Personel Davranışı', 'staff_service'),
    ('calisanlarin destegi harikaydi', 'Personel Davranışı', 'staff_service'),
    ('hizmet kalitesi cok basariliydi', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti yardimseverdi', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti cok hizliydi', 'Personel Davranışı', 'staff_service'),
    ('yardimseverlik mukemmeldi', 'Personel Davranışı', 'staff_service'),
    ('calisanlarin destegi aninda yardimci oldular', 'Personel Davranışı', 'staff_service'),
    ('hizmet kalitesi harikaydi', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti cok basariliydi', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti yavastir', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti hic yardimci olmadilar', 'Personel Davranışı', 'staff_service'),
    ('yardimseverlik yetersizdi', 'Personel Davranışı', 'staff_service'),
    ('calisanlarin destegi baslarindan savdilar', 'Personel Davranışı', 'staff_service'),
    ('hizmet kalitesi basarisizdi', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti berbatti', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti yavastir', 'Personel Davranışı', 'staff_service'),
    ('yardimseverlik hic yardimci olmadilar', 'Personel Davranışı', 'staff_service'),
    ('calisanlarin destegi yetersizdi', 'Personel Davranışı', 'staff_service'),
    ('hizmet kalitesi baslarindan savdilar', 'Personel Davranışı', 'staff_service'),
    ('personel hizmeti basarisizdi', 'Personel Davranışı', 'staff_service'),
    ('iletisim cok basariliydi', 'Personel Davranışı', 'communication'),
    ('dil bilgisi anlasilirdi', 'Personel Davranışı', 'communication'),
    ('turkce iletisim dil problemi yoktu', 'Personel Davranışı', 'communication'),
    ('personelin ingilizcesi sorunsuzdu', 'Personel Davranışı', 'communication'),
    ('yabanci dil seviyesi iletisim cok kolaydi', 'Personel Davranışı', 'communication'),
    ('iletisim cok akiciydi', 'Personel Davranışı', 'communication'),
    ('dil bilgisi cok basariliydi', 'Personel Davranışı', 'communication'),
    ('turkce iletisim anlasilirdi', 'Personel Davranışı', 'communication'),
    ('personelin ingilizcesi dil problemi yoktu', 'Personel Davranışı', 'communication'),
    ('yabanci dil seviyesi sorunsuzdu', 'Personel Davranışı', 'communication'),
    ('iletisim iletisim cok kolaydi', 'Personel Davranışı', 'communication'),
    ('iletisim turkce bilmiyorlar', 'Personel Davranışı', 'communication'),
    ('dil bilgisi ingilizce yetersizdi', 'Personel Davranışı', 'communication'),
    ('turkce iletisim iletisim kuramadik', 'Personel Davranışı', 'communication'),
    ('personelin ingilizcesi derdimizi anlatamadik', 'Personel Davranışı', 'communication'),
    ('yabanci dil seviyesi zayifti', 'Personel Davranışı', 'communication'),
    ('iletisim hic anlasamadik', 'Personel Davranışı', 'communication'),
    ('dil bilgisi turkce bilmiyorlar', 'Personel Davranışı', 'communication'),
    ('turkce iletisim ingilizce yetersizdi', 'Personel Davranışı', 'communication'),
    ('personelin ingilizcesi iletisim kuramadik', 'Personel Davranışı', 'communication'),
    ('yabanci dil seviyesi derdimizi anlatamadik', 'Personel Davranışı', 'communication'),
    ('iletisim zayifti', 'Personel Davranışı', 'communication'),
    ('profesyonellik ust duzeydeydi', 'Personel Davranışı', 'professionalism'),
    ('personelin liyakati mukemmeldi', 'Personel Davranışı', 'professionalism'),
    ('calisan kiyafetleri islerini ciddiye aliyorlardi', 'Personel Davranışı', 'professionalism'),
    ('diksiyon kalitesi cok profesyonelceydi', 'Personel Davranışı', 'professionalism'),
    ('is disiplini guzeldi', 'Personel Davranışı', 'professionalism'),
    ('profesyonellik disiplinliydi', 'Personel Davranışı', 'professionalism'),
    ('personelin liyakati ust duzeydeydi', 'Personel Davranışı', 'professionalism'),
    ('calisan kiyafetleri mukemmeldi', 'Personel Davranışı', 'professionalism'),
    ('diksiyon kalitesi islerini ciddiye aliyorlardi', 'Personel Davranışı', 'professionalism'),
    ('is disiplini cok profesyonelceydi', 'Personel Davranışı', 'professionalism'),
    ('profesyonellik guzeldi', 'Personel Davranışı', 'professionalism'),
    ('profesyonellik hic yoktu', 'Personel Davranışı', 'professionalism'),
    ('personelin liyakati disiplinsizlerdi', 'Personel Davranışı', 'professionalism'),
    ('calisan kiyafetleri kiyafetleri kirliydi', 'Personel Davranışı', 'professionalism'),
    ('diksiyon kalitesi is bilmezlerdi', 'Personel Davranışı', 'professionalism'),
    ('is disiplini amatorceydi', 'Personel Davranışı', 'professionalism'),
    ('profesyonellik yetersizdi', 'Personel Davranışı', 'professionalism'),
    ('personelin liyakati hic yoktu', 'Personel Davranışı', 'professionalism'),
    ('calisan kiyafetleri disiplinsizlerdi', 'Personel Davranışı', 'professionalism'),
    ('diksiyon kalitesi kiyafetleri kirliydi', 'Personel Davranışı', 'professionalism'),
    ('is disiplini is bilmezlerdi', 'Personel Davranışı', 'professionalism'),
    ('profesyonellik amatorceydi', 'Personel Davranışı', 'professionalism'),
]

@pytest.mark.parametrize("text,expected_dept,expected_aspect", TEST_CASES)
def test_massive_hotel_absa_mapping(text, expected_dept, expected_aspect):
    result = OntologyService.map_aspect_to_department("", text)
    assert result.get("departmentLabel") == expected_dept, f"Text: {text} | Expected Dept: {expected_dept} | Got: {result.get('departmentLabel')}"
    assert result.get("aspect_key") == expected_aspect, f"Text: {text} | Expected Aspect: {expected_aspect} | Got: {result.get('aspect_key')}"
